// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAnwQZm6-QXkagIyFPL6gAZdiUyj6Jmc',
    appId: '1:242756677195:web:375d505bd655cacd8767ce',
    messagingSenderId: '242756677195',
    projectId: 'my-multiplayer-word-game',
    authDomain: 'my-multiplayer-word-game.firebaseapp.com',
    storageBucket: 'my-multiplayer-word-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs89aGDK7af_EJ1Nn1jV1C7FjJXMm3LJ0',
    appId: '1:242756677195:android:8680abea5a039e108767ce',
    messagingSenderId: '242756677195',
    projectId: 'my-multiplayer-word-game',
    storageBucket: 'my-multiplayer-word-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMSSr7src0BGylPH5bytWvlXH0beHwAE',
    appId: '1:242756677195:ios:a911367858886e468767ce',
    messagingSenderId: '242756677195',
    projectId: 'my-multiplayer-word-game',
    storageBucket: 'my-multiplayer-word-game.firebasestorage.app',
    iosBundleId: 'com.example.wordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMSSr7src0BGylPH5bytWvlXH0beHwAE',
    appId: '1:242756677195:ios:a911367858886e468767ce',
    messagingSenderId: '242756677195',
    projectId: 'my-multiplayer-word-game',
    storageBucket: 'my-multiplayer-word-game.firebasestorage.app',
    iosBundleId: 'com.example.wordGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHAnwQZm6-QXkagIyFPL6gAZdiUyj6Jmc',
    appId: '1:242756677195:web:6aefd05d2997e4538767ce',
    messagingSenderId: '242756677195',
    projectId: 'my-multiplayer-word-game',
    authDomain: 'my-multiplayer-word-game.firebaseapp.com',
    storageBucket: 'my-multiplayer-word-game.firebasestorage.app',
  );
}
